export const GET_ALL_CATEGORY_PROJECT_API = 'GET_ALL_CATEGORY_PROJECT_API'
export const GET_ALL_CATEGORY_PROJECT_ACTION = 'GET_ALL_CATEGORY_PROJECT_ACTION'

export const GET_PROJECT_LIST_API = 'GET_PROJECT_LIST_API'
export const GET_PROJECT_LIST_ACTION = 'GET_PROJECT_LIST_ACTION'

export const GET_PROJECT_DETAIL_API = 'GET_PROJECT_DETAIL_API'
export const GET_PROJECT_DETAIL_ACTION = 'GET_PROJECT_DETAIL_ACTION'

export const GET_ALL_TASK_TYPE_API = 'GET_ALL_TASK_TYPE_API'
export const GET_ALL_TASK_TYPE_ACTION = 'GET_ALL_TASK_TYPE_ACTION'

export const GET_ALL_PRIORITY_API = 'GET_ALL_PRIORITY_API'
export const GET_ALL_PRIORITY_ACTION = 'GET_ALL_PRIORITY_ACTION'

export const GET_ALL_STATUS_API = 'GET_ALL_STATUS_API'
export const GET_ALL_STATUS_ACTION = 'GET_ALL_STATUS_ACTION'

export const GET_TASK_DETAIL_API = 'GET_TASK_DETAIL_API'
export const GET_TASK_DETAIL_ACTION = 'GET_TASK_DETAIL_ACTION'

export const UPDATE_TASK_DETAIL_API = 'UPDATE_TASK_DETAIL_API'
export const UPDATE_TASK_DETAIL_ACTION = 'UPDATE_TASK_DETAIL_ACTION'

export const UPDATE_TASK_STATUS_API = 'UPDATE_TASK_STATUS_API'
export const UPDATE_TASK_STATUS_ACTION = 'UPDATE_TASK_STATUS_ACTION'

export const INSERT_COMMENT_API = 'INSERT_COMMENT_API'
export const INSERT_COMMENT_ACTION = 'INSERT_COMMENT_ACTION'

export const GET_ALL_COMMENTS_API = 'GET_ALL_COMMENTS_API'
export const GET_ALL_COMMENTS_ACTION = 'GET_ALL_COMMENTS_ACTION'

export const DELETE_COMMENT_API = 'DELETE_COMMENT_API'
export const DELETE_COMMENT_ACTION = 'DELETE_COMMENT_ACTION'

export const UPDATE_COMMENT_API = 'UPDATE_COMMENT_API'
export const UPDATE_COMMENT_ACTION = 'UPDATE_COMMENT_ACTION'
