export const LOGIN_USER_ACTION = 'LOGIN_USER_ACTION'
export const LOGIN_USER_API = 'LOGIN_USER_API'

export const SIGN_UP_USER_ACTION = 'SIGN_UP_USER_ACTION'
export const SIGN_UP_USER_API = 'SIGN_UP_USER_API'

export const GET_USER_LIST_API = 'GET_USER_LIST_API'
export const GET_USER_LIST_ACTION = 'GET_USER_LIST_ACTION'
